
trigger:
- master

pool:
  vmImage: node:16.17.0-alpine3.15

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
  - task: Yarn
    displayName: 'Install Yarn'
    - script: |
      yarn install
      yarn run build
    displayName: 'yarn install and build'  

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      - script: echo Deploying the code