# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
pool:
  vmImage: ubuntu-latest
# Set variables
variables:
  uiSource: 'src'
  uiBuild: 'build'
  
  serviceConnection: Azure subscription 1 (40a59f90-b176-4bfa-ace9-9630edebfd6b)
  appServiceName: mvpWebApp
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    pushd $(uiSource)
    npm install
    npm run build
    popd
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
 
#- stage: Deploy
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(serviceConnection)'
    appName: '$(appServiceName)'
    appType: 'webAppLinux'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'